# Generated by Django 3.2.4 on 2021-06-15 16:47

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('circle_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('circle_name', models.CharField(max_length=40)),
                ('circle_name_hn', models.CharField(max_length=40)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'circle',
                'ordering': ['circle_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mauza',
            fields=[
                ('mauza_id', models.AutoField(primary_key=True, serialize=False)),
                ('mauza_name', models.CharField(blank=True, max_length=40, null=True)),
                ('mauza_name_hn', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateTimeField()),
                ('thana_no', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'mauza',
                'ordering': ['mauza_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('panchayat_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('panchayat_name', models.CharField(blank=True, max_length=40, null=True)),
                ('panchayat_name_hn', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'panchayat',
                'ordering': ['panchayat_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('thana_id', models.AutoField(primary_key=True, serialize=False)),
                ('thana_name', models.CharField(blank=True, max_length=40, null=True)),
                ('thana_name_hn', models.CharField(blank=True, max_length=40, null=True)),
                ('thana_no', models.CharField(blank=True, max_length=4, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'thana',
                'ordering': ['thana_name_hn'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vivad',
            fields=[
                ('vivad_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('thana_no', models.CharField(blank=True, max_length=4, null=True)),
                ('khata_no', models.CharField(blank=True, max_length=10, null=True)),
                ('khesra_no', models.CharField(blank=True, max_length=10, null=True)),
                ('rakwa', models.CharField(blank=True, max_length=5, null=True)),
                ('plot_type', models.CharField(blank=True, max_length=50, null=True)),
                ('abhidhari_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cause_vivad', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_order', models.CharField(blank=True, max_length=200, null=True)),
                ('case_status', models.BooleanField(blank=True)),
                ('next_date', models.DateTimeField(blank=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vivad',
                'ordering': ['vivad_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField(blank=True)),
                ('remarks', models.TextField(blank=True, max_length=200)),
                ('vivad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vivad')),
            ],
            options={
                'db_table': 'hearing',
                'ordering': ['vivad', '-hearing_date'],
            },
        ),
    ]
