# Generated by Django 3.2.4 on 2021-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['circle_id']},
        ),
        migrations.AlterModelOptions(
            name='mauza',
            options={'ordering': ['mauza_id']},
        ),
        migrations.AlterModelOptions(
            name='panchayat',
            options={'ordering': ['panchayat_id']},
        ),
        migrations.AlterModelOptions(
            name='thana',
            options={'ordering': ['thana_name_hn']},
        ),
        migrations.AlterModelOptions(
            name='vivad',
            options={'ordering': ['vivad_id']},
        ),
    ]
