# Generated by Django 3.2.4 on 2021-08-08 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='is_govtPlot',
            field=models.BooleanField(blank=True, default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='plotdetail',
            name='plot_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='plotdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vivad',
            name='plot',
            field=models.ForeignKey(blank=True, db_column='plot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plotdetail', to_field='plot_uuid'),
        ),
        migrations.AddField(
            model_name='vivad',
            name='register_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vivad',
            name='vivad_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='vivad',
            field=models.ForeignKey(blank=True, db_column='vivad', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vivad', to_field='vivad_uuid'),
        ),
    ]
