# Generated by Django 3.2.4 on 2021-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
