# Generated by Django 3.2.4 on 2021-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plotdetail_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='is_first_present',
            field=models.BooleanField(blank=True, default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='hearing',
            name='is_second_present',
            field=models.BooleanField(blank=True, default=False, max_length=1),
        ),
    ]
