# Generated by Django 3.2.4 on 2021-06-15 16:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210615_1649'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='vivad',
            name='first_party_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vivad',
            name='first_party_contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='vivad',
            name='first_party_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vivad',
            name='second_party_address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vivad',
            name='second_party_contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='vivad',
            name='second_party_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
