# Generated by Django 3.2.4 on 2021-06-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210628_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='mauza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.mauza'),
        ),
    ]
