# Generated by Django 3.2.4 on 2021-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210615_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivad',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
