# Generated by Django 3.2.4 on 2021-08-18 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_plotdetail_plot_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdetail',
            name='plot_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
