# Generated by Django 3.2.4 on 2021-08-19 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_plotdetail_plot_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivad',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
