# Generated by Django 3.2.4 on 2021-06-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210616_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauza',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.circle'),
        ),
        migrations.AddField(
            model_name='mauza',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.panchayat'),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.circle'),
        ),
        migrations.AddField(
            model_name='thana',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.circle'),
        ),
        migrations.AddField(
            model_name='vivad',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.circle'),
        ),
        migrations.AddField(
            model_name='vivad',
            name='mauza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.mauza'),
        ),
        migrations.AddField(
            model_name='vivad',
            name='panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.panchayat'),
        ),
    ]
