# Generated by Django 3.2.4 on 2021-08-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_plotdetail_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivad',
            name='plot',
        ),
    ]
