# Generated by Django 3.2.4 on 2021-08-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_vivad_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='vivad',
            field=models.ForeignKey(blank=True, db_column='vivad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.vivad', to_field='vivad_uuid'),
        ),
    ]
