# Generated by Django 3.2.4 on 2021-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210625_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivad',
            name='case_status',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Closed')], default=0),
        ),
    ]
