version: '3.7'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres
    env_file: ./.docker-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    init: true
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  jupyter:
    init: true
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./frontend/react-app:/usr/src/app